name: HeroFreedomMod
version: 1.95
description: My attempt at making a freedom plugin.
author: Camzie99
website: http://fop.us.to
 
main: net.camtech.fopmremastered.FreedomOpModRemastered
database: false
softdepend: [BukkitTelnet, BarAPI, CoreProtect]